# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-09 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='return_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('amount', models.FloatField()),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Borrower')),
                ('investor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Investor')),
            ],
        ),
    ]
