# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-09 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_return_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='investment_track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.FloatField()),
                ('date_invested', models.DateField()),
                ('time_invested', models.TimeField()),
                ('investor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Investor')),
            ],
        ),
    ]
