# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-09 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_investment_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment_track',
            name='investor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
        ),
        migrations.AlterField(
            model_name='return_payment',
            name='investor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='investor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
        ),
    ]
