# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0003_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.CharField(max_length=100),
        ),
    ]
