# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0005_auto_20160709_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='investment_track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.FloatField()),
                ('date_invested', models.DateField()),
                ('time_invested', models.TimeField()),
                ('investor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.user')),
            ],
        ),
        migrations.CreateModel(
            name='return_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('amount', models.FloatField()),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.Borrower')),
                ('investor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.user')),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='investor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.user'),
        ),
    ]
